.PHONY: build

GOL_CMD_FILE='./cmd/game_of_life/main.go'
GOL_WITH_RAND_CMD_FILE='./cmd/gol_with_rand/main.go'

run_gol:
	go run ${GOL_CMD_FILE}

run_gol_with_rand:
	go run ${GOL_WITH_RAND_CMD_FILE}

run: run_gol
